---
title: " "
description: |
  
author:
  - name: Cuiping Wei
    url: 
date: August 30, 2020
categories: 
  - COVID-19
output:
  distill::distill_article:
    self_contained: false
bibliography: references.bib
preview: images/COVID-19.png
resources:
  exclude:
    data/
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load-libraries}
#remotes::install_github("GuangchuangYu/nCov2019")
#remotes::install_github("GuangchuangYu/chinamap")
library(tidyverse)
library(knitr)
library(dplyr)
library(kableExtra)
library(plotly)
library(nCov2019)
library(leafletCN)
library(chinamap)
library(rgdal)
library(maptools)
library(mapproj)
library(ggsn)
library(xml2)
library(rvest)
library(RColorBrewer)
library(gganimate)
```

```{r}
#remotes::install_github("GuangchuangYu/nCov2019")
#remotes::install_github("GuangchuangYu/chinamap")

```

```{r}
covid19_tot <- get_nCov2019(lang='en')
hubei <- covid19_tot['Hubei', ] %>%
  filter(name != is.na(name) )
```

```{r}
load("data/CityMapDatas.Rda")  
map_hubei<-map %>% 
  filter(NAME_1 == 'Hubei') %>% 
  mutate(name = recode(NAME_2,
                       "Enshi Tujia and Miao" = "Enshi",
                       "Suizhou Shi" = "Suizhou",
                       "Xiangfan" = "Xiangyang"))
```


```{r}
hubei_map_data <- data.frame(hubei$name,
                 cut(hubei$confirm, c(0,10,100,500,1000,10000, 60000),
                     labels=c("1~9","10~99","100~500","500~999","1000~9999","≥10000"),
                     include.lowest=TRUE, right=FALSE))  
names(hubei_map_data) <- c("name", "confirm")
```

```{r}
hubei_map_data <- map_hubei %>%
  left_join(hubei_map_data, by="name") 
```


```{r}
theme_p <- theme(axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.text.x = element_blank(),
                  axis.text.y = element_blank(),
                  #plot.title = element_text(face = "bold"),
                  plot.background = element_rect(fill="white"),
                  panel.background = element_rect(fill="white"))
```

```{r}

ggplot(hubei_map_data) +
  geom_sf(aes(fill=confirm, geometry=geometry)) +
  geom_sf_text(aes(label=name, geometry=geometry), color='blue') +
  scale_fill_brewer(palette="Blues") +
  theme(plot.title=element_text(hjust=0.5))  +
  guides(fill=guide_legend(reverse=TRUE))+
  theme_p
  
```

```{r}
covid_history <- load_nCov2019(lang='en')
cn_dat <- covid_history []
```

```{r}
hubei_his_dat<- cn_dat %>% 
  filter(province == "Hubei",
         time >= "2019-12-20" & time <= "2020-04-30") %>% 
  group_by(time) %>% 
  summarise(cum_confirm = sum(cum_confirm),
            cum_dead = sum(cum_dead),
            cum_heal = sum(cum_heal))
  
h_line <- hubei_his_dat %>% 
  ggplot(aes(x = as.Date(time, "%m/%d/%Y"))) +
    geom_line(aes(y = cum_confirm, color = "Confirmed")) +
    geom_line(aes(y = cum_dead, color = "Deaths")) +
    geom_line(aes(y = cum_heal, color = "Recovered")) +
    transition_reveal(as.Date(time, "%m/%d/%Y")) +
    scale_color_manual( "", 
      breaks = c("Confirmed", "Deaths", "Recovered"),
      values = c("black", "red", "steelblue")) +
    labs(title = "COVID-19 in Hubei, China",
         subtitle = "Data from R packages **nCov2019**",
         x = "Time",
         y = "Count") +
    scale_x_date(date_breaks = "2 week",
                 date_labels = "%b %d") +
    theme_light()

h_line
```



```{r gdp_data,eval=FALSE}
#scrape gdp information
url_gdp <- "https://zh.wikipedia.org/wiki/%E6%B9%96%E5%8C%97%E5%90%84%E5%B8%82%E5%B7%9E%E5%9C%B0%E5%8C%BA%E7%94%9F%E4%BA%A7%E6%80%BB%E5%80%BC%E5%88%97%E8%A1%A8"

html_gdp <- read_html(url_gdp)
tbl_gdp <- html_nodes(html_gdp, "table")
gdp_info <- html_table(tbl_gdp[[1]], fill = TRUE) %>% select(1:2)

#rename the columns
names(gdp_info) = c("city", "GDP")
gdp_info$city <- trans_city(gdp_info$city)


```

```{r}
#scrape population information
url_pop <- "https://zh.wikipedia.org/wiki/%E6%B9%96%E5%8C%97%E7%9C%81%E5%90%84%E5%B8%82%E5%B7%9E%E4%BA%BA%E5%8F%A3%E5%88%97%E8%A1%A8"

html_pop <- read_html(url_pop)
tbl_pop <- html_nodes(html_pop, "table")
pop_info <- html_table(tbl_pop[[1]], fill = TRUE) %>% select(1:2)
pop_info <- pop_info[-c(1:2),]

#rename the columns
names(pop_info) = c("city", "population")
pop_info$city <- trans_city(pop_info$city)
```


```{r}
hubei_dat<- hubei %>% 
  select(name, confirm, dead, heal)
```

```{r}
hubei_info <- gdp_info %>% 
  left_join(pop_info, by = "city") %>% 
  left_join(hubei_dat, by = c("city" = "name")) %>% 
  mutate(dead_rate = round(dead / confirm,3),
         population = as.numeric(population)) %>% 
  filter(city != "Wuhan") %>% 
  arrange(-dead) %>% 
  head(10) %>% 
  mutate(log_gdp = log(GDP))
```


```{r}
ggplot(hubei_info, aes(x=population, y=GDP)) +
  geom_point(aes(size=dead, color=city), show.legend = FALSE) +
  geom_text(aes(label=paste(city)), hjust=-.2, size=3,vjust = -.5) +
  geom_abline(intercept=0, slope=6.5, color='red', size=.9, alpha=.5, linetype="dotted") +
  xlim(100, 800) +
  theme_classic() +
  scale_size_continuous(range=c(2,11)) +
  annotate(geom = "text", x=530, y=3500, label="National gdp", size=3) +
  annotate(geom = "text", x=600, y=1200, label="< National gdp",  size=4) +
  annotate(geom = "text", x=250, y=3000, label="> National gdp", alpha=.8, size=4)
```

```{r}
GGally::ggpairs(hubei_info, c(2,3,5))
```

